### ISSUE TITLE
main.cf needs to not contain IPv6, if IPv6 is not configured

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-postfix#13]
If IPv6 is not configured (also see https://github.com/debops/ansible-ferm/issues/11), postfix will grumble about this:

```
send-mail: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
postdrop: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
```

To get rid of this, we need to add
`inet_protocols = ipv4`
to main.cf in case IPv6 is not enabled.

Source: http://unix.stackexchange.com/questions/64414/ipv6-support-is-disabled-warnings

**Comment by drybjed** [comment]
The redesign of the `debops.postfix` role should allow for easy implementation of this option. I'm closing this issue for now, it might be visited after the role repositories are merged in the unified `git` repository.
