### ISSUE TITLE
libsasl2-modules missing

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-postfix#47]
As a mail relay on a debian wheezy i got this error:

```
Jul 24 17:50:56 XXXX postfix/smtp[12619]: warning: SASL authentication failure: No worthy mechs found
```

After installing this pkg it worked: libsasl2-modules

Should be added?

**Comment by drybjed** [comment]
Perhaps if `auth` is enabled in Postfix capabilities. I'll see how to add it with that condition.

**Comment by muelli** [comment]
Currently, the libsasl2-modules package is installed if I read auth_sasl.yml correctly.

Can this issue be closed?

**Comment by drybjed** [comment]
The support for SMTP SASL auth has been moved to the [`debops.saslauthd`](https://github.com/debops/ansible-saslauthd) and [`debops.postconf`](https://github.com/debops/ansible-postconf) Ansible roles. I'm closing this issue as resolved.
