### ISSUE TITLE
Starting latest Postfix playbook from Mailman gives the following error

### ISSUE THREAD

**Issue by stavnstrup** [debops/ansible-postfix#56]
Running a very simple (almost empty) playbook with 

roles:
  - debops.mailman

gives the following error

No variables have been changed or initialized at this stage.

ERROR: Failed to template {{ lookup('task_src', 'postfix/pre_main.yml') }}: lookup plugin (task_src) not found

All mailman/postfix pre-requsite roles exists

and are saved in

    /etc/ansible/roles

Running the command "ansible-galaxy list" gives the following result

- debops.apt_preferences, v0.1.1
- debops.secret, v0.2.2
- debops.postfix, master
- debops.ferm, v0.1.1
- debops.nginx, v0.1.4
- debops.pki, master
- debops.mailman, master

**Comment by drybjed** [comment]
[task_src](https://github.com/debops/debops-playbooks/blob/master/playbooks/lookup_plugins/task_src.py) is one of the custom lookup plugins DebOps uses to sidestep the problem of adding custom tasks to the roles. You can grab it from the link and put it in `lookup_plugins/` directory somewhere where Ansible looks fo them - check generated `ansible.cfg` for possible paths. After this, role should work without issues.

**Comment by stavnstrup** [comment]
Thanks, that worked just fine. I did NOT install debops using  pip but only by using ansible-galaxy.

Did not find any documentation on this issue in "DebObs scripts" or in "debops.postfix".
