### ISSUE TITLE
potentially broken configuration generated from template

### ISSUE THREAD

**Issue by muelli** [debops/ansible-postfix#80]
The configuration debops generated for looks like this:

```
smtp_tls_CApath                 = /etc/ssl/certs# postscreen disabled, required capabilities: +mx|+postscreen
```

which seems to be a bit wrong, because postfix takes it up:

```
# postconf smtp_tls_CApath
smtp_tls_CApath = /etc/ssl/certs# postscreen disabled, required capabilities: +mx|+postscreen
```

It turns out, that the current tls file has no trailing whitespace which causes the following template to be put on the same line.

I guess when including all the template files, it should be made sure that each part starts on a separate line.

**Comment by pwetzel** [comment]
I was just about to create a PR for this. #81 is a better solution than going through every template snippet and making sure it ends with a newline.

**Comment by muelli** [comment]
Now that the PR has been merged, I suppose this bug is fixed.  @pwetzel can you test?

**Comment by pwetzel** [comment]
Tested after the merge, works great. No regressions in my setup. Thanks again for the clever solution.

**Comment by muelli** [comment]
Cool!  Let me close this issue then.

FWIW: I think the templates should have the trailing newline themselves, so feel free to propose the relevant changes.
