### ISSUE TITLE
setting postfix_capabilities has no effect

### ISSUE THREAD

**Issue by muelli** [debops/ansible-postfix#83]
I modified the main.cf template to include the `postfix_capabilities` variable:

```
# Current postfix capabilities: {{ ", ".join(postfix) }}
# Current postfix capabilities: {{ ", ".join(postfix_capabilities) }}
```

Ansible makes it
```
# Current postfix capabilities: local
# Current postfix capabilities: network, postscreen, mx, auth, dnsbl, dnswl, submission, local
```

The documentation is a bit confusing, because the text for both entries is the same.  The changes file, however, states:
```
- Add ``postfix_capabilities`` variable which will define the list of Postfix
  capabilities. The old ``postfix`` variable is still present and will be
  removed at a later time.
```

So I would have assumed that using the "capabilities" variable is the way to go, but the code in the templates only check for `postfix` and not for `postfix_capabilities` (i.e. archive.j2 checks `if 'archive' in postfix`).

If the "postfix" variable is deprecated, then I would expect the documentation to reflect that somehow. Otherwise, I suppose the documentation should make clear what the difference between `postfix` and `postfix_capabilities` is.

**Comment by drybjed** [comment]
Thanks for the bug report. I expected that the `postfix` variable would use the contents of the `postfix_capabilities` variable, but it seens that it doesn't, not sure why. I'll check that out.

**Comment by drybjed** [comment]
This functionality has been redesigned, support for capabilities is now included in the [`debops.postconf`](https://github.com/debops/ansible-postconf) Ansible role. I'm closing this issue as resolved.
