### ISSUE TITLE
DKIM

### ISSUE THREAD

**Issue by asyncopation** [debops/ansible-postfix#90]
Hello, I love the Debops project and would like to contribute.

Unless I missed it, I notice there is currently no implementation for opendkim provisioning in this ansible-postfix (or any Debops) role.  Currently I am executing debops which will provision postfix.  Then I am running a dkim role (https://github.com/sunfoxcz/ansible-dkim) which will provision the opendkim server and make necessary changes to `/etc/postfix/main.cf`.  However, if I then run debops again, the dkim preferences within `/etc/postfix/main.cf` are lost, and the dkim role must be run again to append the configuration.  As a workaround I'm using a local playbook which executes postfix role followed by dkim role.

Is opendkim something you would be interested in adding support for in this role (or perhaps a new Debops role)?  I would be happy to submit a pull request with the necessary changes.

Let me know, and thanks for Debops!

**Comment by drybjed** [comment]
Hi. DKIM would be a great addition, however for that to happen I feel that the 'debops.postfix' role needs to be refactored first. At the moment you can "inject" your own options in the `main.cf` and `master.cf` via Ansible local facts. You can check the `debops.mailman` and `debops.smstools` roles for example usage of `debops.postfix` as a role dependency.

However what I would like to do first is to refactor `debops.postfix` role to use a dependent configuration system similar to what `debops.elasticsearch` and `debops.kibana` use, ie. via a JSON file inside the `secret/` directory. After that adding custom parameters in Postfix configuration should be much simplier.

And yes, a DKIM role should be separate, and use `debops.postfix` as a dependency to pass on its configuration.

**Comment by asyncopation** [comment]
I see.  Thanks for the info and examples.

Is the `debops.postfix` refactor currently being worked on?

**Comment by drybjed** [comment]
@asyncopation Yes, you can check [debops.etc_aliases](https://github.com/debops/ansible-etc_aliases) to see how the role dependency mechanism will be designed for `debops.postfix`. I'm currently rewriting the Postfix role from scratch, the part that managed `/etc/aliases` here will be dropped since this was moved to a separate role.

After `debops.postfix` rewrite is finished, I plan to work on the OpenDKIM role as well.

**Comment by drybjed** [comment]
The support for DKIM is now available via the [`debops.opendkim`](https://github.com/debops/ansible-opendkim) Ansible role. I'm closing this issue as resolved.
