### ISSUE TITLE
Typo in tasks/main.yml

### ISSUE THREAD

**Issue by Skeen** [debops/ansible-postfix#95]
- name: Gnereate Postfix lookup tables

sed -i 's/Gnereate/Generate/g'?

**Comment by drybjed** [comment]
Thanks for the heads up. DebOps development has been moved to a single [DebOps monorepo](https://github.com/debops/debops/) where this issue [is already fixed](https://github.com/debops/debops/blob/master/ansible/roles/debops.postfix/tasks/main.yml#L140) you might consider switching over. :-)

**Comment by Skeen** [comment]
Ah thank you, I wasn't aware.

Can you point me to somewhere explaining the decision to move to a monorepo?

**Comment by drybjed** [comment]
Of course, the discussion can be found on the [`debops-users` mailing list](https://lists.debops.org/pipermail/debops-users/), you can start with [the initial message](https://lists.debops.org/pipermail/debops-users/2017-August/000078.html), discussion took a few months.

**Comment by Skeen** [comment]
Thank you :)
